name: Backup all repos to gitlabwh on a schedule
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  backup:
    strategy:
      max-parallel: 1
      matrix:
        version: [0, 5, 10, 15, 20, 25, 30, 35]
        os: [ubuntu-22.04]
    if: github.repository_owner == 'deepin-community'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "linuxdeepin/jenkins-bridge-client"
          path: jenkins-bridge-client
      - name: Install Client
        run: |
          cd $GITHUB_WORKSPACE/jenkins-bridge-client
          go build .
          sudo install -Dvm755 jenkins-bridge-client -t /usr/bin/
      - uses: actions/checkout@v3
      - run: bash ".github/workflows/backup-all-repos-to-gitlabwh.bash" deepin-community ${{ secrets.BridgeToken }} ${{ matrix.version }}
